baseURL = "/"
languageCode = "fr-fr"
title = "Institut de Recherche Territoire Démocratique"
theme = "biztrox"
summaryLength = "20"

# navigation
[menu]
    
    [[menu.nav]]
    name = "L'institut"
    URL = "/about"
    weight = 2


    [[menu.nav]]
    name = "Qui sommes-nous ?"
    URL = "/team"
    weight = 3
 
    
#    [[menu.nav]]
#    name = "Actualités"
#    URL = "/blog"
#    weight = 4
    
   
    [[menu.nav]]
    name = "Recherches"
    URL = "/project"
    weight = 6
    
    [[menu.nav]]
    name = "Activités"
    URL = "/service"
    weight = 5
 

[params]
logo = "images/logo.png"
mail = "institut@democratique.org"
mobile = "+33695025117"
home = "Accueil"
# google map
gmapAPI = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
mapLatitude = "51.5223477"
mapLongitude = "-0.1622023"
mapMarker = "images/marker.png"
# Google Analitycs
googleAnalitycsID = "Your ID"

# mailchimp subsciption
mailchimpFormAction = "https://themefisher.us9.list-manage.com/subscribe/post?u=f95ece2732a6e9925f2e70a61&amp;id=b1e227529e" # replace this url with yours
mailchimpFormName = "b_f95ece2732a6e9925f2e70a61_b1e227529e" # replace this code with yours


  # meta data
  [[params.meta]]
  name = "description"
  content = "this it a content"
  
  [[params.meta]]
  name = "keywords"
  content = "this it a content"

    # Quote Button
    [params.quoteBtn]
    enable = true
    btnText = "Nous contacter"
    btnURL = "/contact"

    # about
    [params.about]
    enable = true
    bgImage = "images/background/about-bg.jpg"
    title = "Qui sommes-nous ?"
    description = "Formateurs, enseignants, chercheurs, nous étudions les innovations démocratiques."
    [params.about.btn]
    enable = true
    btnText = "En savoir plus"
    btnURL = "/about"

        [[params.about.listLeft]]
        listItem = "Formations"

        [[params.about.listLeft]]
        listItem = "Expertises"
        
        [[params.about.listLeft]]
        listItem = "Conseils"

        [[params.about.listRight]]
        listItem = "Séjours d'études"

        [[params.about.listRight]]
        listItem = "Animations"
        
        [[params.about.listRight]]
        listItem = "Recherches"

    # promo video
    [params.promoVideo]
    enable = true
    heading = "Nos interventions dans les médias"
    videoURL = "https://www.youtube.com/watch?v=_0M8Fc7a13Q"
    title = "MédiapartLive - Gilets jaunes: « Ils veulent décider, pas participer à un grand débat »"

    # cta
    [params.cta]
    enable = false
    bgImage = "images/background/cta.jpg"
    title = "Biztrox give the smart solution for your business"
    btnText = "get a quote"
    btnURL = "#"

    # clients Logo Slider
    [params.logoSlider]
    enable = false
        [[params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-1.png"
        URL = "#"
        
        [[params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-2.png"
        URL = "#"
        
        [[params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-3.png"
        URL = "#"
        
        [[params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-4.png"
        URL = "#"
        
        [[params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-5.png"
        URL = "#"
        
        [[params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-1.png"
        URL = "#"
        
        [[params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-2.png"
        URL = "#"
        
        [[params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-3.png"
        URL = "#"
        
        [[params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-4.png"
        URL = "#"
        
        [[params.logoSlider.sliderItem]]
        image = "images/client-logo/client-logo-5.png"
        URL = "#"

    # footer
    [params.footer]
    logo = "images/logo-footer.png"
    content = "Lorem ipsum dolor amet consectetur adipisicing elit sed eiusm tempor incididunt labore dolore magna aliqua enim."

    # service links
    services = "Services"
    
    # quickLinks
    quickLink = "Quick Link"

    # subscribe
    subscribe = "Subscribe Us"
    subscribeContent = "Lorem ipsum dolor sit amet, consect etur adipisicing. elit sed do eiusmod."

    # copyright
    copyright = ""

        # social icon
        [[params.footer.socialIcon]]
        icon = "ti-facebook"
        URL = "#"

        [[params.footer.socialIcon]]
        icon = "ti-twitter-alt"
        URL = "#"
        
        [[params.footer.socialIcon]]
        icon = "ti-vimeo-alt"
        URL = "#"
        
        [[params.footer.socialIcon]]
        icon = "ti-linkedin"
        URL = "#"

        # service links
        [[params.footer.service]]
        serviceItem = "Company History"
        URL = "#"
        
        [[params.footer.service]]
        serviceItem = "About Us"
        URL = "#"
        
        [[params.footer.service]]
        serviceItem = "Contact Us"
        URL = "#"
        
        [[params.footer.service]]
        serviceItem = "Service"
        URL = "#"
        
        [[params.footer.service]]
        serviceItem = "Privacy Policy"
        URL = "#"

        # quick links
        [[params.footer.quickLinks]]
        quickLinkItem = "Pricing"
        URL = "#"
        
        [[params.footer.quickLinks]]
        quickLinkItem = "FAQs"
        URL = "#"
        
        [[params.footer.quickLinks]]
        quickLinkItem = "Contact Us"
        URL = "#"
        
        [[params.footer.quickLinks]]
        quickLinkItem = "Service"
        URL = "#"
        
        [[params.footer.quickLinks]]
        quickLinkItem = "Privacy Policy"
        URL = "#"

        # bottom links
#        [[params.footer.links]]
#            name = "Legal"
#            URL = "#"
            
#        [[params.footer.links]]
#            name = "Sitemap"
#            URL = "#"
            
#        [[params.footer.links]]
#            name = "Privacy Policy"
#            URL = "#"
            
#        [[params.footer.links]]
#            name = "Terms & Conditions"
#            URL = "#"

    # share blog post
    [[params.sharePost]]
    icon = "ti-facebook"
    URL = "#"
    
    [[params.sharePost]]
    icon = "ti-twitter-alt"
    URL = "#"
    
    [[params.sharePost]]
    icon = "ti-linkedin"
    URL = "#"
    
    [[params.sharePost]]
    icon = "ti-google"
    URL = "#"
        


